### PR TITLE
feat(http-proxy) add support for http/https proxy authorization

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Adds support to `set_proxy_options` for two new options:
- `http_proxy_authorization`, and
- `https_proxy_authorization`

### CODE REVIEW

**Comment by bungle** [comment]
Please do not merge yet. I found an issue in implementation.

**Comment by bungle** [comment]
@pintsized I think this is ready for review. Not sure if you want this to be merged, but it makes possible to use authenticate on proxy servers when using `request_uri`.

**Comment by bungle** [comment]
@pintsized do you think there is a way to get these to upstream?

**Comment by pintsized** [comment]
Hey, thanks for this. Sorry I'm just flat out at the moment, will get to it by the weekend. Sorry, again!

**Pull request merged**
