### PR TITLE
Update documentation to reflect deprecated features

### PR DESCRIPTION
**Pull request by pintsized**
I gave the README a bit of a long overdue overhaul, in the hope that things are much clearer for new users. I also added `WARN` level log statements to the deprecated functions, which could get noisy for some people depending on what they're logging. Any thoughts / opinions on this?

### CODE REVIEW

**Comment by hamishforbes** [comment]
Maybe a config or something to disable deprecation logging? or at least reduce the log level?
Or a module scoped var to only log each deprecation message once?

I can see logging multiple WARNs for every request being very bad in some cases
A high traffic proxy could easily end up logging thousands of extra log lines per second and if you're shipping all those logs somewhere then that could be very expensive or overload the logging infra entirely

**Comment by pintsized** [comment]
Ok yeah, I thought you'd probably say that. I wasn't sure if `WARN` was something typically enabled in production or not? I was actually considering removing them for now, so at least it's documented as deprecated for a while before we start actually logging it. Tricky though, because encouraging people to use this new interface is probably quite important for correctness.

Making it configurable like the `DEBUG` log is easy enough though.

**Comment by hamishforbes** [comment]
Yeah so maybe running at a higher level, like WARN, but only logging it once per function call per worker would be better?
It's not going to spam, but it should be noticeable because they're a higher (lower?) log level

**Comment by pintsized** [comment]
I'm a bit wary of conditional warnings - could make CI flaky for some people. So for now I decided to just use `DEBUG` logging, since this has happened without any notice and will effect everyone, but isn't actually critical. At least developers are very likely to see it in the short term, and then in time we can bump this up if we think it's important.

**Pull request merged**
