### PR TITLE
Add Content-Length: 0 header on POST/PUT/PATCH when the body is absent

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Some servers are a bit strict about `POST`/`PUT`/`PATCH` request without body and without `Content-Length` header.

According to:
https://tools.ietf.org/html/rfc7230#section-3.3.2

> a Content-Length header field is normally sent in a POST request even
> when the value is 0 (indicating an empty payload body)

This PR will add `Content-Length` header on such case for `POST`/`PUT`/`PATCH`.

### CODE REVIEW

**Comment by hamishforbes** [comment]
Is doing this for `POST` requests **only** correct? 
The RFC states
> ... the request method defines a meaning for an enclosed payload body.  For example, a Content-Length header field is normally sent in a POST request ...

Do any other methods qualify? `PUT` or `PATCH`?

Otherwise, looks good, thanks for including a test :)

**Comment by bungle** [comment]
@hamishforbes it looks like, e.g. HTTPie adds it to `PUT`, `PATCH`, `CONNECT` too, but not to `GET´. I am not really sure what is the industry standard for this :-). Need to read more.

**Comment by bungle** [comment]
@hamishforbes according to this discussion, adden PUT and PATCH makes senwe. I will modify the PR: https://bugs.python.org/issue23539

**Comment by bungle** [comment]
@hamishforbes the PR is now fixed to set `Content-Length: 0` also on `PUT` and `PATCH` in addition to `POST`, and the tests were updated accordingly.

**Comment by hamishforbes** [comment]
Nice, yeah I think if someone is using any other methods where this is appropriate they're doing something advancedish and should be able to figure out setting this header themselves 👍 

Fixes #184

**Comment by shaynevanasperen** [comment]
Thanks @bungle @hamishforbes for doing this 👍

**Comment by bungle** [comment]
@hamishforbes thank you! can you also prepare `luarocks` release?

**Pull request merged**
